[build]
command = "npm run build"
publish = ".next"

[functions]
# Specify bundler and external dependencies
node_bundler = 'esbuild'
external_node_modules = ["sharp"]

[[plugins]]
package = "@netlify/plugin-nextjs"
