[[redirects]]
from = '/api/*'
to = '/.netlify/functions/api/:splat'
status = 200

[functions]
node_bundler = 'esbuild'
external_node_modules = ["sharp"]

[[plugins]]
package = "@netlify/plugin-nextjs"

